use lxml<=5.1.0, 5.1.1 breaks extruct
ImportError: cannot import name '_ElementStringResult' from 'lxml.etree'
(...) Did you mean: '_ElementUnicodeResult'?